// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import type { Infer as __Infer } from 'spacetimedb-lynx';

// Import all reducer arg schemas
import type DecrementCounterReducer from '../decrement_counter_reducer';
import type IncrementCounterReducer from '../increment_counter_reducer';
import type LoginReducer from '../login_reducer';
import type LogoutReducer from '../logout_reducer';
import type RegisterReducer from '../register_reducer';
import type ResetCounterReducer from '../reset_counter_reducer';

export type DecrementCounterParams = __Infer<typeof DecrementCounterReducer>;
export type IncrementCounterParams = __Infer<typeof IncrementCounterReducer>;
export type LoginParams = __Infer<typeof LoginReducer>;
export type LogoutParams = __Infer<typeof LogoutReducer>;
export type RegisterParams = __Infer<typeof RegisterReducer>;
export type ResetCounterParams = __Infer<typeof ResetCounterReducer>;
