// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb-lynx";

// Import all reducer arg schemas
import DecrementCounterReducer from "../decrement_counter_reducer";
import IncrementCounterReducer from "../increment_counter_reducer";

export type DecrementCounterParams = __Infer<typeof DecrementCounterReducer>;
export type IncrementCounterParams = __Infer<typeof IncrementCounterReducer>;

