// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
  TypeBuilder as __TypeBuilder,
  t as __t,
} from 'spacetimedb-lynx';
import { UserRole } from './types';

export default __t.row({
  userId: __t.u32().primaryKey().name('user_id'),
  username: __t.string(),
  passwordHash: __t.string().name('password_hash'),
  get role() {
    return UserRole;
  },
  createdAt: __t.timestamp().name('created_at'),
});
