// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb-lynx";

export default __t.row({
  identity: __t.identity().primaryKey(),
  attemptCount: __t.u32().name("attempt_count"),
  windowStartedAt: __t.timestamp().name("window_started_at"),
});
