// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
  TypeBuilder as __TypeBuilder,
  t as __t,
} from 'spacetimedb-lynx';

export const AppUser = __t.object('AppUser', {
  userId: __t.u32(),
  username: __t.string(),
  passwordHash: __t.string(),
  get role() {
    return UserRole;
  },
  createdAt: __t.timestamp(),
});
export type AppUser = __Infer<typeof AppUser>;

export const AuthSession = __t.object('AuthSession', {
  identity: __t.identity(),
  userId: __t.u32(),
  username: __t.string(),
  get role() {
    return UserRole;
  },
  loggedInAt: __t.timestamp(),
});
export type AuthSession = __Infer<typeof AuthSession>;

export const Counter = __t.object('Counter', {
  id: __t.u32(),
  count: __t.i32(),
});
export type Counter = __Infer<typeof Counter>;

export const LoginAttempt = __t.object('LoginAttempt', {
  identity: __t.identity(),
  attemptCount: __t.u32(),
  windowStartedAt: __t.timestamp(),
});
export type LoginAttempt = __Infer<typeof LoginAttempt>;

// The tagged union or sum type for the algebraic type `UserRole`.
export const UserRole = __t.enum('UserRole', {
  Student: __t.unit(),
  Parent: __t.unit(),
  Teacher: __t.unit(),
  Admin: __t.unit(),
});
export type UserRole = __Infer<typeof UserRole>;
