# # Uncomment the next line to define a global platform for your project
# # platform :ios, '9.0'

# target 'Hello-Lynx-OC' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!

#   # Pods for Hello-Lynx-OC

# end

source 'https://cdn.cocoapods.org/'

platform :ios, '10.0'

target 'Hello-Lynx-OC' do
  pod 'Lynx', '3.6.0', :subspecs => [
    'Framework',
  ]


  # integrate image-service, log-service, and http-service
  pod 'LynxService', '3.6.0', :subspecs => [
      'Image',
      'Log',
      'Http',
  ]

  # ImageService
  pod 'SDWebImage','5.15.5'
  pod 'SDWebImageWebPCoder', '0.11.0'

  # XElement
  pod 'XElement', '3.6.0'
end